[build]
  publish = "."                        # publish root (static files are in repo root)
  functions = "netlify/functions"      # functions directory

[dev]
  command = "npx netlify-cli@latest dev"
